-- CreateEnum
CREATE TYPE "TimZone" AS ENUM ('AMERICA_CHICAGO', 'AMERICA_NEW_YORK', 'AMERICA_DENVER', 'AMERICA_LOS_ANGELES', 'ASIA_KOLKATA');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "timezone" "TimZone" NOT NULL DEFAULT 'AMERICA_CHICAGO';
