import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { Separator } from "@/components/ui/separator";
import { Toaster } from 'sonner';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Exponential Everyday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${montserrat.className} bg-white text-teal-950`}>
        <div className='container px-4 mx-auto overflow-x-hidden lg:px-0'>
          <Navbar />
          {children}
          <Separator />
          <div className='flex items-center justify-center h-10 text-sm'>
            <footer>Footer Content</footer>
          </div>
          <Toaster richColors position="top-right" duration={5000} />
        </div>
      </body>
    </html>
  );
}
