import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { Separator } from "@/components/ui/separator";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Exponential Everyday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.className} bg-white text-teal-950`}
      >
        <div className='overflow-x-hidden mx-auto container px-4 lg:px-0'>
          <Navbar />
          {children}
        <Separator/>
        <div className="h-10 text-sm flex items-center justify-center">
          <footer>Footer Content</footer>
        </div>
        </div>
      </body>
    </html>
  );
}
