
export default function Home() {
  return (
    <main>
      <div className='flex justify-between h-[calc(100dvh-7rem)] gap-4 overflow-hidden'>
        <div className='rounded-md w-full shadow-sm overflow-y-auto'>
          <p>HOME PAGE CONTENT</p>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis aut ducimus quo natus repudiandae. Velit fuga sequi quidem quo doloremque nostrum est quisquam delectus quis, unde non, magni possimus explicabo.
          Impedit nesciunt sunt deserunt officia pariatur amet minus repudiandae, aperiam commodi nulla qui repellat explicabo, dolorem nobis rerum iste magni assumenda mollitia quas eligendi iusto aliquam ducimus totam voluptatibus? Incidunt?
          Veritatis voluptatum omnis tempora eos commodi dignissimos. Non repellat libero corrupti deleniti aperiam ullam, error rem a? Vitae, consectetur quaerat voluptate aut fuga temporibus sequi tenetur ab, asperiores quisquam quibusdam!
          Fugit veritatis ut dolore similique reiciendis quae doloremque iste repudiandae vitae magnam distinctio voluptates accusamus pariatur, veniam facilis itaque sed. Dolorum sequi, qui commodi est porro animi voluptates magnam vero?
          Alias totam tenetur itaque, blanditiis natus iusto temporibus praesentium, nam error cum necessitatibus, eveniet numquam nihil est quos explicabo tempore? Nemo placeat soluta eveniet magnam temporibus debitis iusto quia! Sit!
          Aspernatur nulla eaque exercitationem animi, temporibus nostrum necessitatibus praesentium iusto dolores minima explicabo sint, facilis qui magnam molestias cum autem, totam facere sed blanditiis illum ipsum? Nihil ex ut quaerat.
          Non quis et dignissimos, deleniti error, aspernatur, velit quidem amet omnis facilis delectus est autem! Adipisci nulla mollitia reprehenderit eaque similique aut, est, ducimus vero eos cupiditate iure optio illum!
          Similique cumque expedita quam dolorum facilis temporibus eaque autem fuga asperiores nobis consectetur, consequatur quos consequuntur quisquam eligendi ad sit voluptates officia odio id animi eius quaerat eum! Quos, eveniet?
          Consectetur cumque fugit fuga fugiat molestiae, molestias architecto deleniti iusto aliquid natus, ipsam quod itaque minus magni odit veniam? Laudantium laborum suscipit maxime dolorum vitae rem quas similique itaque nihil?
          At soluta molestiae nesciunt, consequatur provident dolore cum facilis dignissimos odit porro quasi iure, nulla fugiat alias et. Amet quidem aspernatur a. Qui nesciunt quae temporibus harum quasi recusandae ipsam.
          Exercitationem ipsum commodi illum ipsa qui? Earum ad hic illum, incidunt enim cumque ipsa numquam rerum, delectus quisquam recusandae nostrum. Nisi, aperiam non dolores ipsam labore distinctio sint dolor perferendis?
          Temporibus deserunt, laboriosam alias accusamus reprehenderit impedit placeat quidem consequatur aliquid eligendi quod et amet commodi culpa quam voluptatem in animi, non harum dolore quibusdam mollitia! Nam eius quaerat at!
          Animi, atque enim praesentium officiis, dicta modi, quam placeat optio id dolorum nisi laudantium necessitatibus ipsa. Fugiat pariatur, ad vero aut excepturi nisi fuga deleniti vitae voluptatum ratione, inventore ullam.
          Aperiam sint, provident iste consectetur sit maxime, ad voluptas deserunt vitae corrupti facere pariatur? Error sunt quas illo laudantium molestias doloremque architecto commodi nulla repudiandae, sapiente ipsa natus cumque aspernatur.
          Nostrum sint sunt non ducimus natus, quis saepe, facilis unde eveniet autem odio nihil? Minus error explicabo laudantium deleniti commodi quia eligendi nam dolorum rem sequi? Cum fugiat tempore quod.
          Iusto ducimus ipsa, blanditiis ea, voluptas architecto quasi tempore, alias eligendi quis quam officiis illum impedit harum explicabo aliquid quidem porro. Blanditiis veritatis tempora voluptatibus, ullam nostrum earum nihil odit.
          Quam, voluptatibus vel! Eius porro similique reprehenderit, magnam dolorum quo eum consectetur repudiandae corrupti obcaecati sunt quaerat quam iusto deleniti voluptatibus quos consequuntur ipsam, nemo sed eaque omnis quasi. Perspiciatis.
          Dolorem unde corporis voluptas facilis similique beatae modi accusamus non provident illum laboriosam quos, dolore repellat error possimus dignissimos, voluptates reprehenderit vitae commodi. Nisi distinctio, iure a fugit aspernatur repellendus.
          Esse, error! Iste error sint expedita voluptatem magni rerum optio deserunt ut nobis. Magnam tempore corporis, hic assumenda placeat facilis id culpa? Sed voluptate fugit fuga tenetur quibusdam corporis at.
          Modi dolores, hic ab quia aperiam error aspernatur est id dicta? Placeat ratione excepturi facere nihil provident et dolores earum tenetur delectus, ipsum aut numquam pariatur dolore nemo officia magni!
          Similique minima, quo exercitationem porro accusamus totam deserunt omnis a non quam hic autem cum facilis dolores sequi aliquid ipsa ex, consectetur nisi quae rem corporis! Porro maiores nihil mollitia!
          Quae laborum culpa unde animi molestiae laboriosam ad, optio incidunt, corrupti a, porro excepturi error facilis? Illo voluptates fugit accusantium! Repudiandae nesciunt libero amet sint commodi eos odit minus porro.
          Accusantium, veritatis accusamus blanditiis, voluptas iusto aut voluptatibus dolores ullam in odio quaerat itaque at officia, quasi error rem id labore? Amet, deleniti suscipit. Doloremque perspiciatis in dolores ullam. Culpa?
          Deserunt alias inventore sunt, perspiciatis fuga ducimus eveniet quia dolores, esse et cum ad soluta commodi dolor? Quibusdam repellendus quam ad, ea velit, deserunt voluptatum hic cum blanditiis, est ab?
          Rerum perspiciatis nulla natus magni incidunt esse suscipit impedit? Enim voluptate dolorem ipsam, veritatis ipsa obcaecati, tenetur placeat fugiat odio omnis inventore repudiandae quae dolores! Deserunt esse sunt voluptatem laborum.
          Odit voluptates deserunt voluptas repellat aut amet eos suscipit minima temporibus nam quasi saepe a corporis quo culpa, consequuntur possimus non minus sequi nobis. Illo iure ex ullam excepturi inventore!
          Ipsum vitae ut atque reiciendis suscipit obcaecati aut accusantium, soluta rerum iste quos, cumque sequi libero totam nesciunt accusamus, iusto recusandae maxime eos dicta expedita ullam? Mollitia beatae vitae doloremque!
          Itaque eligendi laborum, ipsum expedita est magnam vitae accusantium consequuntur quo cum vero provident aspernatur autem deserunt eius totam debitis accusamus perferendis qui porro assumenda ducimus? Labore cum similique dicta?
          Ut mollitia a optio quia vitae maxime sed quis, fugiat vel molestiae accusamus, recusandae, rem dolorem nostrum. Excepturi optio adipisci quae, accusantium sint, inventore recusandae architecto beatae itaque soluta facere.
          Aliquid aperiam cupiditate assumenda, repellat commodi, aut error tempora blanditiis tempore eaque molestiae nam nobis omnis iure reiciendis. Fugit molestiae atque iure excepturi corrupti laudantium repellendus, fuga omnis qui doloribus?
          Porro odio harum natus aut fuga ab repudiandae eveniet aliquam nihil itaque culpa, dolores veritatis ex consectetur libero distinctio similique, officiis nisi possimus sint pariatur repellendus quidem. Dolorum, optio repudiandae.
          Ratione eaque quibusdam earum tempore porro laudantium, eveniet reiciendis quam molestias iusto, necessitatibus soluta laborum! Praesentium, assumenda a quidem culpa porro veniam quaerat amet, natus tempore sunt at odio sint.
          Explicabo iste nostrum reprehenderit fugit autem deserunt velit, necessitatibus neque eaque nam quaerat perferendis. Corrupti atque ipsa enim. Earum consequuntur explicabo saepe labore repellendus aspernatur qui necessitatibus corrupti beatae et.
          Perspiciatis facere ipsam fuga odio saepe laudantium dicta alias cupiditate reprehenderit optio deleniti quia delectus animi, itaque ducimus corrupti voluptatem placeat labore quas quidem dolore eveniet neque illum ea. Sit.
          Reprehenderit rem numquam placeat quidem itaque, omnis soluta magni alias sapiente dolore fugiat atque voluptas vel libero odit aut debitis totam ipsum assumenda nisi unde doloremque. Delectus error accusamus magni.
          Molestias eos harum ab quasi rerum beatae qui dolor perferendis eveniet eum similique debitis, fugit dolorum laudantium error? Dolores ex reprehenderit nobis accusantium saepe quas blanditiis, consectetur nesciunt consequatur sed?
          Magnam atque molestiae, recusandae perspiciatis expedita, totam magni maxime possimus asperiores saepe officia nemo minima vero illum nobis amet vel quas eum consequuntur! Fugiat ratione officiis ea repellendus. Exercitationem, voluptatibus?
          Ipsa officiis beatae deleniti exercitationem in doloremque quo! Illo, eum delectus! Molestias, animi neque. Quod, nemo labore impedit voluptatem eaque tenetur eum dolorem totam possimus. Libero eaque vero hic tenetur!
          Velit fugit illum, consequatur facilis expedita accusamus incidunt ducimus, sunt necessitatibus laudantium repellendus quasi numquam! Repellendus architecto repudiandae, exercitationem quis modi, alias cum ipsum facere nemo eligendi error quaerat nesciunt.
          Enim beatae magni libero, ipsum eveniet, eum ad id architecto maiores itaque porro deleniti provident repudiandae iure deserunt tenetur! Nemo repellat, dicta expedita enim sunt delectus aperiam ipsa esse quod.
          Quam magnam, nihil voluptatem non officia voluptate eligendi placeat vero dolores eaque minus similique rem quae ad nesciunt sapiente impedit labore sed odit facilis necessitatibus. Autem accusantium expedita magni sint.
          Dolorum debitis, veritatis fugiat reprehenderit facilis rerum vel maiores eos nostrum, dolores laudantium aut cum eveniet repellat, officiis doloribus officia totam distinctio suscipit iusto quod aliquam optio commodi! A, distinctio!
          Inventore tempora est vero natus tenetur. Iure nemo ducimus vitae molestiae provident, quae aspernatur eius voluptatum veritatis recusandae minima nam facere. Quasi iusto beatae fuga voluptatem quod ex numquam sit?
          Saepe repellendus nulla dolorum ex ipsam assumenda rerum vel veritatis alias, odit aspernatur ab ipsa ea quisquam dolor quidem consequuntur nobis? Labore perspiciatis eaque pariatur soluta minus beatae ad alias.
          Ratione, eaque ad! Beatae aliquid rerum sequi esse fuga, libero molestiae quaerat quod exercitationem quos perspiciatis corrupti laboriosam atque quisquam repudiandae reprehenderit ea voluptatibus a, minus veniam vero fugit maiores!
          Libero suscipit hic iure nam est dolorem necessitatibus tempore cum debitis, dignissimos animi voluptatum soluta odio! Minus, maxime repellendus earum doloribus accusantium pariatur harum delectus dolore molestias sapiente architecto quidem.
          Ipsa hic labore doloribus perferendis quidem animi dolore voluptates laudantium aliquam commodi molestias vero quas dicta consequuntur deserunt aspernatur, ab aut repudiandae. Cumque totam ad distinctio atque veniam necessitatibus voluptas!
          Fuga aspernatur beatae nostrum magni quaerat alias officiis numquam recusandae dolorem vero expedita impedit voluptates dolore est eius unde repellat optio, soluta animi, molestias distinctio sunt eos amet? At, dolorem.
          Rem reiciendis iusto id. Amet sit quisquam aperiam dicta unde, sed quod consequuntur atque nisi repudiandae nemo repellat deserunt necessitatibus? Facilis consequatur ab corrupti aspernatur iste et, rerum incidunt fugit.
          Tempora repellat ipsam voluptates autem nulla minus vitae quos obcaecati officiis quibusdam ipsum voluptatibus perspiciatis cumque, facilis at veritatis neque eum porro voluptatum perferendis. Neque obcaecati sed rerum odio. Laudantium.
          Maiores sint quibusdam qui ipsa fuga alias est quod hic pariatur dolores facere, odio ad at amet, eos et quia explicabo quas cum magnam velit ratione mollitia? Doloremque, dolores? Saepe.
          Fugit facilis tempora nihil atque expedita numquam voluptate cum porro, adipisci dolorem cumque eos sapiente illo nostrum molestiae, eaque modi officiis iste odio deserunt? Mollitia laborum omnis possimus itaque voluptates?
          Recusandae sapiente accusamus dolore sed provident doloribus minima, natus fugit, eaque magnam tenetur obcaecati laboriosam fugiat explicabo ipsam voluptatum eos, quas cumque voluptatem quibusdam aliquam! Nam suscipit ducimus aliquam reprehenderit.
          Beatae, aut hic sed molestias illum sit facilis asperiores aliquam vero quibusdam. Tempora beatae corporis, voluptatem obcaecati, voluptas nihil quisquam ad ab illo impedit numquam esse odit. Beatae, facere ipsa.
          Nihil atque unde error quidem impedit eligendi nam quo dolor, dignissimos culpa debitis! Amet perspiciatis alias repellat facere libero nulla accusamus quasi voluptates rem id eum, delectus est fugit? Voluptatibus.
          Repellendus ducimus expedita, omnis voluptates odio nam perferendis labore vel sit voluptate minima consectetur quisquam qui quod obcaecati sint soluta dignissimos eos delectus. Modi quo veritatis nam, iure soluta tempore.
          Inventore neque maiores deserunt, dolorem nihil natus a repellendus qui illum ea perferendis molestias explicabo nemo corporis officiis ducimus, hic cum porro fugiat ullam odio perspiciatis! Atque voluptas esse at?
          Commodi, quis? Voluptatum assumenda impedit sed ex voluptate asperiores dolor corrupti. Quis laudantium, consequuntur numquam, porro ullam obcaecati sunt dolorum asperiores molestiae odit eaque qui beatae voluptatem nam itaque quos?
          Atque expedita iure dolore qui quam sit reprehenderit praesentium libero necessitatibus quaerat, fugit maiores rem doloremque nulla cum possimus? Cum numquam neque sequi eius unde eum facilis error dolore quas?
          Sequi provident dignissimos autem, mollitia odio tempora obcaecati fugit officiis asperiores optio odit ullam hic amet accusantium aspernatur. Error officiis commodi dolores ullam neque cum rerum atque, numquam adipisci recusandae!
          Sunt id tempore, optio consectetur aliquam beatae ab voluptatibus esse odio officiis quam, accusamus vel repellendus recusandae! Architecto eum adipisci quidem eligendi facere, ea ex incidunt dolorem, error dignissimos nulla!
          Provident earum blanditiis amet repudiandae laborum. Ut voluptatem soluta dolorem dolores harum quidem odit sit dolor temporibus officia voluptatum quia, voluptates ratione nobis velit? Ipsa unde minus eligendi iste sequi.
          Commodi ullam reprehenderit quae atque aliquid pariatur hic ipsam, architecto alias iste quibusdam nemo quis ab animi libero similique ratione eveniet voluptatibus suscipit, veritatis aliquam saepe praesentium. Possimus, rem vero.
          Officia nobis enim tempore sequi animi alias rerum, earum aliquid nisi, incidunt error atque blanditiis perspiciatis! Tenetur aliquam harum consequuntur voluptatibus, sunt asperiores facere veniam, velit nobis incidunt quibusdam excepturi?
          Eum alias assumenda perspiciatis quidem nostrum libero adipisci, corporis error, aliquid consequatur quo aperiam quis fuga asperiores ducimus, quibusdam labore? Iste eius repudiandae aliquid quidem nostrum dignissimos, deleniti quasi eligendi!
          Molestiae dicta, adipisci labore pariatur possimus atque ad unde ex. Fugit, doloribus labore. Quia tempora rem impedit quo quibusdam, iure eligendi ea quam iusto molestias, cupiditate quas odio temporibus vero?
          Expedita recusandae voluptatem cumque eaque molestiae sequi adipisci vero placeat laborum qui quia asperiores nesciunt aliquam mollitia eos blanditiis cum eius deserunt ad maxime illum maiores, libero sint! Dolore, qui?
          Quis maxime illum libero ab aperiam omnis? Nobis nesciunt minus accusamus? Ipsa asperiores doloribus aperiam eum sapiente repellendus saepe, expedita tempore nisi magni accusamus nesciunt architecto quasi! Optio, expedita cum.
          Minima explicabo voluptatum voluptas similique optio blanditiis quas eligendi nisi, nostrum totam tempore laborum incidunt unde dicta, natus ea vitae porro dolore est dolorem repudiandae deserunt. Earum neque aut quis.
          Quibusdam ducimus doloribus sed praesentium, alias officia obcaecati molestiae quisquam voluptas aperiam, facilis quas, assumenda suscipit quia ullam commodi veritatis maxime iste. Accusantium quo odio, minus nesciunt quaerat praesentium dolorum?
          Ipsam illo quod officia consequatur, quo dolorem vitae et harum distinctio laborum mollitia aut explicabo libero fugiat aliquid doloremque rerum qui. Amet, illum! Dignissimos at magni, illo veniam consectetur laudantium!
          Officia neque, quibusdam incidunt distinctio, expedita deleniti nulla reiciendis rem sapiente quod, laudantium consequuntur excepturi itaque? Ipsum saepe hic cumque autem labore officia exercitationem, iste sint officiis itaque deleniti rerum.
          Nam in asperiores recusandae illum sapiente at quas libero veritatis quod enim doloremque nobis quia distinctio itaque quis repellendus dolorum iure expedita, minus esse cumque architecto! Quaerat voluptates aliquam quae.
          Animi optio nisi tempore et sapiente adipisci consectetur corrupti vero itaque sunt ullam, tenetur quidem sequi ex odio quo exercitationem. Hic eveniet culpa, neque perspiciatis cupiditate totam! Deserunt, voluptatibus ipsam.
          Provident totam nisi unde nihil aperiam, porro in voluptatem! Ducimus tempore consequatur expedita perferendis exercitationem, dicta omnis ad, et repellat repellendus dolores quia. Eius obcaecati sapiente minima placeat inventore amet?
          Ab sapiente quidem corporis quibusdam. Expedita temporibus, cum, facere consequuntur nobis numquam quo blanditiis cupiditate aspernatur laudantium quod saepe reprehenderit rerum incidunt. Iusto assumenda est quos quo praesentium! Nostrum, natus!
          Ut soluta facere necessitatibus explicabo rerum neque, sequi dolor atque eveniet nemo dolorem eaque ipsa distinctio. Error provident ex ipsum ullam hic esse, iure quis enim quia vel expedita a?
          Libero sit similique distinctio beatae recusandae debitis maxime laudantium incidunt sequi? Deleniti velit totam laboriosam, recusandae saepe nesciunt quisquam possimus dolore dignissimos necessitatibus ipsum, fuga et accusamus odit maiores natus.
          Obcaecati exercitationem officiis illo illum molestias, labore unde, explicabo quas ab similique eum. Perspiciatis ipsum ab laborum doloribus quae quos nobis veniam. Commodi hic perspiciatis ut recusandae? Minima, laborum dolores!
          Iusto, accusamus. Molestiae corrupti sapiente quos! Sit nisi obcaecati minima ut natus saepe non odio consequatur? Fuga totam quae tenetur sequi doloremque explicabo animi. Quidem magnam vitae quaerat dolores quis?
          Aliquid obcaecati provident vel nam nobis magni impedit quod dicta culpa. Quod ullam incidunt cupiditate commodi tenetur error consectetur esse harum eveniet nihil maiores illo, odio id voluptatum earum optio?
          Tempore a est quidem nulla vitae similique odit. Voluptatum nesciunt consectetur quo exercitationem fugit ipsa, delectus porro? Nisi voluptas, eveniet hic magnam, possimus qui consectetur amet culpa porro totam deleniti!
          Laborum, officiis modi. Et repellat quasi perspiciatis numquam officiis. Facilis animi deserunt aliquid impedit reiciendis. Itaque quaerat, ad inventore sed voluptate magnam officiis tempora amet eius repudiandae, adipisci fugiat ut.
          Vero quo deleniti perspiciatis id aliquid blanditiis? Delectus quam rem itaque blanditiis at molestias facilis ducimus deleniti vel eos voluptate aliquam odit illum quisquam laboriosam mollitia expedita, optio error accusantium!
          Quod maxime at eligendi veritatis voluptates est cupiditate ullam dicta. Distinctio officia molestias provident aut tempora expedita fugit, quibusdam quidem dolore. Aut nisi, corporis doloremque unde quibusdam cumque! Ad, nobis.
          Corrupti vero veniam eveniet voluptatibus debitis fuga ipsa assumenda aspernatur necessitatibus modi, quasi magnam, hic voluptate optio obcaecati est similique illum corporis reprehenderit cumque. Deleniti tenetur totam molestiae sequi. Minus?
          Maxime expedita repellendus alias recusandae fuga architecto quis repudiandae dolor natus corporis aut magni ab molestias voluptas libero, error illo, exercitationem sed similique beatae numquam? Odit, repudiandae. Ipsam, impedit eligendi?
          Voluptatem, odit. Quis veritatis recusandae voluptates ex consectetur maxime placeat, exercitationem iusto numquam corporis harum eaque officiis eligendi dolorum at optio libero quos voluptatum ad explicabo. Totam autem atque earum?
          Iusto non voluptas dolore quo atque, minima repellat accusantium eveniet tempora cupiditate eligendi harum dolor voluptatibus neque sint ipsum laboriosam molestiae totam nostrum facilis! Saepe cupiditate repudiandae voluptatibus repellat animi!
          Labore, fuga officia adipisci esse aperiam sunt consequatur nihil molestiae eius optio quas laboriosam ipsam dolores quos a. Velit ab doloremque accusamus delectus voluptates quae modi explicabo eaque sit doloribus.</p>
        </div>
      </div>
    </main>
  );
}
